# github action to be manually run to create a github release using release-it and lerna-changelog
name: Tag Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release_it:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Symlink package.json to root
        run: ln -s assets/package.json package.json

      # Runs a set of commands using the runners shell
      - name: Install dependencies and Create release
        run: |
          echo Run in assets/
          cd assets
          echo Setup git identity
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          echo Install dependencies
          npm install
          echo Run release-it
          npx release-it minor --ci
        env:
          GITHUB_AUTH: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
